{% set name = "tropycal" %}
{% set version = "0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tropycal-{{ version }}.tar.gz
  sha256: 694c43e2628a493a24cb1f1a8fee6fe921000164896e7d908e0eef851b909e9e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - geopy >=1.18.1
    - matplotlib-base >=2.2.2
    - networkx >=2.0.0
    - numpy >=1.14.3
    - pandas >=0.23.0
    - python >=3.6
    - requests >=2.22.0
    - scipy >=1.1.0
    - xarray >=0.10.7

test:
  imports:
    - tropycal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tropycal/tropycal
  summary: Package for retrieving and analyzing tropical cyclone data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
